// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgT06dx7jGkfHSul4uEG4Xj8mnj0lvP-Y',
    appId: '1:347493945317:web:16c6b147b56911df63a90c',
    messagingSenderId: '347493945317',
    projectId: 'brainboxide-6eaaa',
    authDomain: 'brainboxide-6eaaa.firebaseapp.com',
    storageBucket: 'brainboxide-6eaaa.firebasestorage.app',
    measurementId: 'G-PN3L1KX602',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn6tQcDRhWSh_kekDWKudLMpsbVUfrIB4',
    appId: '1:347493945317:android:b4aec1be0cbdb44363a90c',
    messagingSenderId: '347493945317',
    projectId: 'brainboxide-6eaaa',
    storageBucket: 'brainboxide-6eaaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgT06dx7jGkfHSul4uEG4Xj8mnj0lvP-Y',
    appId: '1:347493945317:web:8d18d6e6c32d7b7d63a90c',
    messagingSenderId: '347493945317',
    projectId: 'brainboxide-6eaaa',
    authDomain: 'brainboxide-6eaaa.firebaseapp.com',
    storageBucket: 'brainboxide-6eaaa.firebasestorage.app',
    measurementId: 'G-ZWBBN5N9VB',
  );
}
